### ISSUE TITLE
Practica 1

### ISSUE THREAD

**Issue by ObedG** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-ObedG#2]
Análisis de dos aplicaciones que hagan uso de la realidad aumentada

[Practica 1.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-ObedG/files/6143793/Practica.1.pdf)

**Comment by AxayacatlS** [comment]
Calificacion 19

**Comment by josealfredo79** [comment]
Bien hecho y realizado
